- name: Joindre le domaine
  win_shell: | 
    $Domain = "katrina.irma.local"
    $User = "Administrator@katrina.irma.local"
    $Password = "Azertyuiop68."
    $Cred = New-Object System.Management.Automation.PSCredential ($User, (ConvertTo-SecureString $Password -AsPlainText -Force))

    Add-Computer -DomainName $Domain  -Credential $Cred  -Force

- name: Reboot host after domain join
  win_reboot: